import test, { chromium } from '@playwright/test'

test("Edit a Lead",async({page})=>{
    await page.goto("http://leaftaps.com/opentaps/control/main")
    await page.locator('#username').fill("DemoSalesManager")
    await page.locator('[name=PASSWORD]').fill("crmsfa")
    await page.locator('.decorativeSubmit').click()
    await page.locator(`text='CRM/SFA'`).click()
    await page.locator(`text='Leads'`).click()
    await page.locator(`//a[text()='Find Leads']`).click()
    await page.locator(`[name=firstName]`).last().fill('Rahul')
    await page.locator(`//button[text()='Find Leads']`).click()
    await page.locator(`//a[text()='Rahul']`).first().click()//need help
    await page.locator(`//a[text()='Edit']`).click()
    await page.locator(`#updateLeadForm_companyName`).fill('Update Test')
    await page.locator(`#updateLeadForm_annualRevenue`).fill('100,000')
    await page.locator('#updateLeadForm_departmentName').fill('Packing')
    await page.locator(`#updateLeadForm_description`).fill('Update Lead with new revenue')
    await page.locator(`[name=submitButton]`).first().click()
    const cName=await page.locator(`#viewLead_companyName_sp`).textContent()
    const aRevenue=await page.locator(`#viewLead_annualRevenue_sp`).textContent()
    const dName=await page.locator(`#viewLead_departmentName_sp`).textContent()
    const desc=await page.locator(`#viewLead_description_sp`).textContent()
    const title =await page.title()
    console.log('Update company name is '+cName)
    console.log(`Updated annual revenue is `+aRevenue)
    console.log(`Updated department name is `+dName)
    console.log('Updated description is '+desc)
    console.log('Title is '+title)
})