import test, { chromium } from '@playwright/test'

test("Create Lead ",async({page})=>{
    await page.goto("https://login.salesforce.com/?locale=in")
    await page.locator('#username').fill("ravindran.ramdas@testleaf.com")
    await page.locator('[name=pw]').fill("RaviTestleaf#1432")
    await page.locator('#Login').click()
    await page.locator('.slds-icon-waffle').click()
    await page.locator(`//button[@aria-label='View All Applications']`).click()
    await page.locator(`//input[@class='slds-input']`).fill('Sales')
    await page.locator(`//p[@title='Manage your sales process with accounts, leads, opportunities, and more']`).click()
    await page.locator(`(//span[text()='Leads'])[1]`).click()
    await page.locator(`//div[@title='New']`).click()
    await page.locator(`[name=salutation]`).click()
    await page.locator(`//span[contains(text(),'Mr.')]`).click()
    await page.locator(`[name=lastName]`).fill('Sahu')
    await page.locator(`[name=Company]`).fill('Testleaf')
    await page.locator(`//button[text()='Save']`).last().click()
    await page.waitForTimeout(2000)
})